# -*- coding: utf-8 -*-
"""assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y5h1Tu2xhKmbs-NSvPaysO5WKr9kJOvm

UNDERSTANDING STRINGS LITERALS

**single quotes** = we use single quotes for short string.. where is no any type of coma or quotes.
**Double quotes** = "We use double quotes where a single quote is already present... If we enclose a single quote within single quotes, it will show an error, so double quotes are used."
**tripple quotes** = We use triple quotes for multi-line strings... If double quotes are already present in the string, we will use triple quotes there .
"""

name = 'sana'

text =''' She said,
"I'm going to the store." '''

sentence = "I'm going to the store."

myHobbies = ''' read books
 eating food
 playing games . '''

print(name)
print(text)
print(sentence)
print(myHobbies)



# Strings Method Practice

firstname = 'sana'
lastname ='siyal'
full_name = firstname + " " + lastname

print(full_name.upper())
print(full_name.lower())
print(full_name.capitalize()  )

messy_text = "     python programming is fun!     "

print(messy_text.rstrip())
print(messy_text.lstrip())
print(messy_text.strip())
print(messy_text.replace("fun" , "amazing"))
print(messy_text.count("i"))

sentence = "The quick brown fox jumps over the lazy dog"

print(sentence.split())

words = ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']
result = '-'.join(words)
print(result)

sentence = "The quick brown fox jumps over the lazy dog"
word = "The"
if word in sentence:
  print("word is available")
else:
   print("word is not available")

sentence = "The quick brown fox jumps over the lazy dog"
print(sentence.find("fox"))

"""**f-strings**"""

name = "sana"
age = 25
language = "next.js"

print(f"My name is {name} and I'm {age} years old. I enjoy programming in {language}, it's my favourite!")
print(f"In 5 years, I will be {age + 5} years")

"""**Combining String Methods with F-Strings **


"""

from datetime import datetime

first_name = input("Enter your first name:")
last_name = input("Enter your last name:")
birth_year = input("Enter your birth year:")

print(first_name.capitalize())
print(last_name.capitalize())

current_year = datetime.now().year
age = current_year - int(birth_year)

username = {first_name + last_name + str(age)}
print(username)

profile = f'profile: name: {first_name}{last_name} , age: {age} username:{username}'
print(profile)