# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6yWjIMxp3sh145ajoG3CG9YzjHA5j1T
"""



"""**assignment # 02**

**calculator**
"""

print("lets explore calculator")

num1 = int(input("enter your number:"))
choice = input("select anyone operator (+ , - , * , /):")
num2 = int(input("enter your number:"))


if choice == "+":
  print(f"Result: {num1 + num2}")
elif choice == "-":
  print(f"Result: {num1 - num2}")
elif choice == "*":
  print(f"Result: {num1 * num2}")

elif choice == "/":
 print(f"Result: {num1 / num2}")
else:
 print("invalid")

"""**Grade system**"""

marks = int(input("Enter your percentage:"))

if marks >= 90:
  print("congratulations! you got A+ grade")
elif marks == 80:
    print("you got A grade")
elif marks >= 70:
  print("you got B grade!")
elif marks >= 60:
  print("you got C grade!")
elif marks >= 50:
  print("D grade!")
else:
  print("you are fail!")